spring:
  application:
    name: product-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/berry}
    username: ${DB_USER:berry}
    password: ${DB_PASSWORD:berry}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:very-secret-key-for-local-dev-please-change}
    expiration-minutes: 5256000
  storage:
    root-dir: ${STORAGE_ROOT:uploads}
  users-file: ${APP_USERS_FILE:users.txt}
