name: Deploy API to VPS

on:
  push:
    branches: [ "main" ]
    paths:
      - "product-api/**"
      - ".github/workflows/deploy-api.yml"
      - "product-android/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            if [ ! -d /opt/berry/.git ]; then
              git clone git@github.com:diplomas-2026/berry.git /opt/berry
            fi
            cd /opt/berry
            git checkout main
            git pull --ff-only origin main
            cd /opt
            docker compose up -d --build berry-api
